// Generated by CoffeeScript 1.10.0
(function() {
  var React, Yang,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Yang = require('yang-js');

  React = require('react');

  module.exports = (require('./yang-react.yang')).bind({
    'extension(component)': function() {
      return {
        global: true,
        scope: {
          action: '0..n',
          anydata: '0..n',
          leaf: '0..n',
          'leaf-list': '0..n',
          list: '0..n'
        },
        resolve: function() {
          var required;
          required = ['constructor', 'render'];
          return this["extends"](required.map((function(_this) {
            return function(x) {
              if (_this.locate("action(" + x + ")") == null) {
                return _this.constructor.parse("action " + x + ";");
              }
            };
          })(this)));
        },
        construct: function(data, ctx) {
          var component, self;
          this.debug("making React.Component class");
          self = this;
          component = (function(superClass) {
            extend(_Class, superClass);

            function _Class(props) {
              _Class.__super__.constructor.call(this, self.apply(props));
            }

            return _Class;

          })(React.Component);
          this.debug(component);
          return component;
        }
      };
    }
  });

}).call(this);
